# Generated by Django 3.2.5 on 2022-05-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
