# Generated by Django 3.2.5 on 2022-05-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0002_remove_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
